baseURL: https://paywallhub.com/
languageCode: en-us
title: PaywallHub
canonifyurls: true
paginate: 3
theme: hugo-theme-lean-launch-page-modified
# googleAnalytics: "G-123456"
params:
  tagline: "lolol"
  # twitter: "https://twitter.com/MyNewProduct"
  # instagram: "https://instagram.com/MyNewProduct"
  github: "https://github.com/MyNewProduct"
  images:
    - "favicon.png"